// Code generated by "stringer -type CipherSuite"; DO NOT EDIT.

package fscp

import "strconv"

const _CipherSuite_name = "ECDHERSAAES128GCMSHA256ECDHERSAAES256GCMSHA384"

var _CipherSuite_index = [...]uint8{0, 23, 46}

func (i CipherSuite) String() string {
	i -= 1
	if i >= CipherSuite(len(_CipherSuite_index)-1) {
		return "CipherSuite(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CipherSuite_name[_CipherSuite_index[i]:_CipherSuite_index[i+1]]
}
